name: SomNetworkCord
version: '${project.version}'
main: SomNetworkCord.SomCore
api-version: '1.20'
folia-supported: true

commands:
  SncReload:
    permission: snc.reload
    description: description
    usage: /<command>
